# Generated by Django 4.0.4 on 2022-05-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_info.city')),
                ('street_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_info.street')),
            ],
        ),
    ]
