# Generated by Django 4.0.4 on 2022-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_info', '0002_rename_city_id_shop_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='house_number',
            field=models.IntegerField(default=1),
        ),
    ]
