# Generated by Django 4.0.4 on 2022-05-27 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_info', '0004_alter_shop_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='house_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
